spring.application.name=write-blog
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.datasource.url=jdbc:mysql://localhost:3306/write_blog

# ?i?n ?úng User/Pass b?n dùng trong DBeaver
spring.datasource.username=root
spring.datasource.password=Dantruong@30122020

# Gi? nguyên dòng này ?? code Java t? ??ng t?o b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver